# Generated by Django 3.2 on 2022-07-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_id'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_concepts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_designs',
            field=models.IntegerField(default=1),
        ),
    ]
