# Generated by Django 3.2 on 2022-07-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220719_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_of_designs',
        ),
    ]
