# Generated by Django 3.2 on 2022-08-12 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_of_concepts',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
