# Generated by Django 3.2 on 2022-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_number_of_concepts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_of_concepts',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
