# Generated by Django 3.2 on 2022-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_of_concepts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_designs',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
